import { User, Client, ServiceRequest } from './types';
import { subDays, subHours } from 'date-fns';

export const users: User[] = [
  {
    id: 'user-1',
    name: 'Shaira Haman',
    email: 'shairahaman.csc@gmail.com',
    role: 'admin',
    avatarUrl: 'https://picsum.photos/seed/admin/100/100',
  },
  {
    id: 'user-2',
    name: 'Shaik King',
    email: 'sskingshaikpro@gmail.com',
    role: 'technician',
    avatarUrl: 'https://picsum.photos/seed/tech/100/100',
  },
];

export const clients: Client[] = [
  {
    id: 'client-1',
    name: 'Innovate Inc.',
    email: 'contact@innovate.com',
    phone: '123-456-7890',
    address: '123 Tech Park, Silicon Valley, CA',
    createdAt: subDays(new Date(), 5).toISOString(),
  },
  {
    id: 'client-2',
    name: 'Solutions LLC',
    email: 'support@solutions.io',
    phone: '234-567-8901',
    address: '456 Business Blvd, New York, NY',
    createdAt: subDays(new Date(), 12).toISOString(),
  },
  {
    id: 'client-3',
    name: 'Quantum Corp',
    email: 'admin@quantum.dev',
    phone: '345-678-9012',
    address: '789 Enterprise Way, Chicago, IL',
    createdAt: subDays(new Date(), 25).toISOString(),
  },
  {
    id: 'client-4',
    name: 'NextGen Systems',
    email: 'help@nextgen.sys',
    phone: '456-789-0123',
    address: '101 Future Drive, Austin, TX',
    createdAt: subDays(new Date(), 40).toISOString(),
  },
];

export const serviceRequests: ServiceRequest[] = [
  {
    id: 'req-1',
    title: 'Server Maintenance',
    description: 'The main server is running slow and needs a check-up. Users are reporting long load times.',
    clientId: 'client-1',
    clientName: 'Innovate Inc.',
    status: 'Completed',
    priority: 'High',
    assignedToId: 'user-2',
    assignedToName: 'Shaik King',
    createdAt: subDays(new Date(), 10).toISOString(),
    updatedAt: subDays(new Date(), 8).toISOString(),
    completedAt: subDays(new Date(), 8).toISOString(),
  },
  {
    id: 'req-2',
    title: 'New Software Installation',
    description: 'Need to install the new CRM software on 5 workstations.',
    clientId: 'client-2',
    clientName: 'Solutions LLC',
    status: 'In Progress',
    priority: 'Medium',
    assignedToId: 'user-2',
    assignedToName: 'Shaik King',
    createdAt: subDays(new Date(), 5).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'req-3',
    title: 'Network Outage',
    description: 'The entire office network is down. We need immediate assistance as this is critical.',
    clientId: 'client-3',
    clientName: 'Quantum Corp',
    status: 'Pending',
    priority: 'High',
    createdAt: subHours(new Date(), 2).toISOString(),
    updatedAt: subHours(new Date(), 2).toISOString(),
  },
  {
    id: 'req-4',
    title: 'Printer Not Working',
    description: 'The printer on the 2nd floor is not connecting to the network.',
    clientId: 'client-1',
    clientName: 'Innovate Inc.',
    status: 'Pending',
    priority: 'Low',
    createdAt: subDays(new Date(), 1).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'req-5',
    title: 'Email Configuration',
    description: 'A new employee needs their email configured on their laptop and phone.',
    clientId: 'client-4',
    clientName: 'NextGen Systems',
    status: 'In Progress',
    priority: 'Medium',
    assignedToId: 'user-2',
    assignedToName: 'Shaik King',
    createdAt: subHours(new Date(), 8).toISOString(),
    updatedAt: subHours(new Date(), 3).toISOString(),
  },
  {
    id: 'req-6',
    title: 'Cloud Backup Failure',
    description: 'The automated cloud backup failed last night. Please investigate the cause.',
    clientId: 'client-2',
    clientName: 'Solutions LLC',
    status: 'Cancelled',
    priority: 'High',
    createdAt: subDays(new Date(), 2).toISOString(),
    updatedAt: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'req-7',
    title: 'Security System Check',
    description: 'Annual security system audit and vulnerability scan required.',
    clientId: 'client-3',
    clientName: 'Quantum Corp',
    status: 'Completed',
    priority: 'Medium',
    assignedToId: 'user-2',
    assignedToName: 'Shaik King',
    createdAt: subDays(new Date(), 20).toISOString(),
    updatedAt: subDays(new Date(), 15).toISOString(),
    completedAt: subDays(new Date(), 15).toISOString(),
  },
];
